GET http://localhost:4000/account/staff

#########
GET http://localhost:3000/api/account/646f291ba5255bc92c59a32b
#########
DELETE http://localhost:3000/api/account/646f291ba5255bc92c59a32b

#########
POST http://localhost:4000/account/staff
Content-Type: application/json

{
    "username": "Dream",
    "email": "dreammaker.com",
    "phone": "0911707159",
    "password": "coolguywithcoolboots",
    "role": "VEP"
}
#########
POST http://localhost:3000/api/login
Content-Type: application/json

{
    "email": "dreammaker.com",
    "password": "coolguywithcoolboots"
}
#########
PATCH http://localhost:3000/api/account/646f291ba5255bc92c59a32b
Content-Type: application/json

{
    "username": "Beelzebub"
}

#########
POST http://localhost:3000/department
Content-Type: application/json

{
    "name": "Biology",
    "numberOfStudents": 22,
    "students": [
        "646c87a10424bf9d998f03a6"
        ]
}

####

POST http://localhost:3004/api/account/staff
Content-Type: application/json

{
    "username": "AA",
    "email": "dfdf@gmail.com",
    "password": "1234342",
    "role": "REP",
    "phone": "0987654321"
}