#######
POST http://localhost:3007/api/pay
Content-Type: application/json

{
    "amount": "100",
    "currency": "ETB",
    "phone_number": "0912345678",
    "first_name": "Bilen",
    "last_name": "Gizachew"
}

#######
GET http://localhost:3007/api/verify/0808