GET http://localhost:4000/request
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0OGYwODZmM2MyYjM2ZTEzYjdhZGFmMCIsInVzZXJuYW1lIjoiQWJkZWxzZWxhbSIsInJvbGUiOiJSZXNpZGVudCIsImlhdCI6MTY4NzA5NTQzMywiZXhwIjoxNjg3MDk5MDMzfQ.lDH2CQuyriFumQ0bmzikJZVGWlgOrU1jvsfVt-TlAAY

######
DELETE http://localhost:4000/request
######
GET http://localhost:4000/account/staff
######
POST http://localhost:4000/request
Content-Type: application/json

{
  "type": "death",
  "body": {
    "name": "Lucifer",
    "age": 6,
    "fatherName": "God",
    "grandFatherName": "----",
    "placeOfBirth": "Heaven",
    "sex": "M",
    "address": "Hell",
    "educationLevel": "graduate",
    "occupation": "employed",
    "religion": "Satanist",
    "phoneNumber": "0938666666",
    "emergencyContact": "0910000000",
    "witness": {
      "name": "God",
      "idNumber": "06076076",
      "phoneNumber": "0910000000"
    }
  }
}
######
PATCH http://localhost:3000/api/account/648dca7804947808bae9a4d3
Content-Type: application/json

{
  "photo": "Amazing"
}
######
POST http://localhost:4000/account/staff
Content-Type: application/json

{
  "username": "Dream",
  "email": "dreammaker.com",
  "phone": "0911707254",
  "password": "qwerty",
  "role": "VEP"
}
######
POST http://localhost:4000/request
Content-Type: application/json

{
    "type": "id",
    "body": {
      "nameOfChild": "Lucifer Morningstar",
      "sex": "M",
      "placeOfBirth": "Heaven",
      "deliveryMethod": "Created by God Almighty",
      "nationality": "Hell",
      "weight": 666,
      "attendantProfessional": "The Holy Spirit was in attendance the entire time",
      "motherResidentInfo": "6464fa305496f5bffdad2a9e",
      "fatherResidentInfo": "6465f6643b088cf9b06c3d17"
    }
}

######
GET http://localhost:3001/api/birth/pending
######